// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(authenticated)/(dashboard)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/(dashboard)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/3d-waveform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/3d-waveform">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/3d-waveform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/abrahams-tent/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/abrahams-tent/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/abrahams-tent/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/abrahams-tent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/abrahams-tent">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/abrahams-tent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/board/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/board">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/board/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/builder">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/changelog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/changelog">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/changelog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/harness/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/harness/history">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/harness/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/harness/layers/[layer]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/harness/layers/[layer]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/harness/layers/[layer]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/harness/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/harness">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/harness/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/harness/runs/[runId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/harness/runs/[runId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/harness/runs/[runId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/harness/runs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/harness/runs">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/harness/runs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/harness/suites/[suiteId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/harness/suites/[suiteId]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/harness/suites/[suiteId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/harness/suites/[suiteId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/harness/suites/[suiteId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/harness/suites/[suiteId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/harness/suites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/harness/suites">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/harness/suites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/harness/sweeps/[sweepId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/harness/sweeps/[sweepId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/harness/sweeps/[sweepId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/harness/sweeps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/harness/sweeps">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/harness/sweeps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/ingestion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/ingestion">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/ingestion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/knowledge">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/sandbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/sandbox">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/sandbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/sources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/sources">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/sources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/voice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/voice">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/voice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/wiki/[pageSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/wiki/[pageSlug]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/wiki/[pageSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/wiki/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[slug]/wiki">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/wiki/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/docs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/docs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/editor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/editor">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/editor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/engine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engine">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/engine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/icons-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/icons-test">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/icons-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/loading-indicator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/loading-indicator">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/loading-indicator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/roadmap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roadmap">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/roadmap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/scene-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scene-test">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/scene-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/sessions/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sessions/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/sessions/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sessions">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/simulation/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/simulation/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/simulation/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/simulation/world/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/simulation/world/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/simulation/world/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/voice-debug/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/voice-debug">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/voice-debug/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/voice-test-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/voice-test-2">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/voice-test-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/voice-test-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/voice-test-3">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/voice-test-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/voice-test-4/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/voice-test-4">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/voice-test-4/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/voice-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/voice-test">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/voice-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/voices/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/voices/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/voices/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/voices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/voices">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/voices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/wikis/[id]/ingestion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wikis/[id]/ingestion">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/wikis/[id]/ingestion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/wikis/[id]/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wikis/[id]/knowledge">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/wikis/[id]/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/wikis/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wikis/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/wikis/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/wikis/[id]/pages/[pageSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wikis/[id]/pages/[pageSlug]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/wikis/[id]/pages/[pageSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/wikis/[id]/pages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wikis/[id]/pages">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/wikis/[id]/pages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/wikis/[id]/sources/[sourceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wikis/[id]/sources/[sourceId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/wikis/[id]/sources/[sourceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/wikis/[id]/sources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wikis/[id]/sources">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/wikis/[id]/sources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/wikis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wikis">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/wikis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/worlds/[worldId]/editor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/worlds/[worldId]/editor">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/worlds/[worldId]/editor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/worlds/[worldId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/worlds/[worldId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/worlds/[worldId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/worlds/[worldId]/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/worlds/[worldId]/sessions">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/worlds/[worldId]/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/worlds/[worldId]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/worlds/[worldId]/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/worlds/[worldId]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/worlds/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/worlds/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/worlds/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/worlds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/worlds">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/worlds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/audio/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audio/config">> = Specific
  const handler = {} as typeof import("../../../src/app/api/audio/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/audio/gateway-health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audio/gateway-health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/audio/gateway-health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/audio/reply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audio/reply">> = Specific
  const handler = {} as typeof import("../../../src/app/api/audio/reply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/audio/speak/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audio/speak">> = Specific
  const handler = {} as typeof import("../../../src/app/api/audio/speak/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/audio/transcribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audio/transcribe">> = Specific
  const handler = {} as typeof import("../../../src/app/api/audio/transcribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/changelog/[entryId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/changelog/[entryId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/changelog/[entryId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/changelog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/changelog">> = Specific
  const handler = {} as typeof import("../../../src/app/api/changelog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/bindings/[bindingId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/bindings/[bindingId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/bindings/[bindingId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/brain-model/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/brain-model/history">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/brain-model/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/brain-model/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/brain-model">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/brain-model/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/brain-model/runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/brain-model/runs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/brain-model/runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/directive/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/directive/history">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/directive/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/directive/never-compliance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/directive/never-compliance">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/directive/never-compliance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/directive/promote-candidates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/directive/promote-candidates">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/directive/promote-candidates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/directive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/directive">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/directive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/directive/suggest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/directive/suggest">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/directive/suggest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/evals/runs/[runId]/probes/[probeId]/trace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/evals/runs/[runId]/probes/[probeId]/trace">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/evals/runs/[runId]/probes/[probeId]/trace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/evals/runs/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/evals/runs/[runId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/evals/runs/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/evals/runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/evals/runs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/evals/runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/evals/suites/[suiteId]/fork/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/evals/suites/[suiteId]/fork">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/evals/suites/[suiteId]/fork/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/evals/suites/[suiteId]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/evals/suites/[suiteId]/publish">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/evals/suites/[suiteId]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/evals/suites/[suiteId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/evals/suites/[suiteId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/evals/suites/[suiteId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/evals/suites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/evals/suites">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/evals/suites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/evals/sweeps/[sweepId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/evals/sweeps/[sweepId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/evals/sweeps/[sweepId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/evals/sweeps/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/evals/sweeps">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/evals/sweeps/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/identity/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/identity/history">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/identity/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/identity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/identity">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/identity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/identity/suggest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/identity/suggest">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/identity/suggest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/ingest">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/probe/voice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/probe/voice">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/probe/voice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/sandbox/readiness/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/sandbox/readiness">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/sandbox/readiness/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/system-prompt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/system-prompt">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/system-prompt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/thumbnail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/thumbnail">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/thumbnail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/versions/[versionId]/restore/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/versions/[versionId]/restore">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/versions/[versionId]/restore/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/versions/[versionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/versions/[versionId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/versions/[versionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/versions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/voice-context/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/voice-context">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/voice-context/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/voice-stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/voice-stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/voice-stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/voice-style/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/voice-style/history">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/voice-style/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/voice-style/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/voice-style">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/voice-style/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/voice-style/suggest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/voice-style/suggest">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/voice-style/suggest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/characters/[id]/voice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[id]/voice">> = Specific
  const handler = {} as typeof import("../../../src/app/api/characters/[id]/voice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/communication/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/communication/feedback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/communication/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/communication/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/communication/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/communication/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/communication/scenario/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/communication/scenario">> = Specific
  const handler = {} as typeof import("../../../src/app/api/communication/scenario/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/communication/session/[sessionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/communication/session/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/communication/session/[sessionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/communication/turn/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/communication/turn">> = Specific
  const handler = {} as typeof import("../../../src/app/api/communication/turn/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/evals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/evals">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/evals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dev/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dev/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/docs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/docs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/docs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/engine/trace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/engine/trace">> = Specific
  const handler = {} as typeof import("../../../src/app/api/engine/trace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/features/[featureId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/features/[featureId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/features/[featureId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/features/[featureId]/tickets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/features/[featureId]/tickets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/features/[featureId]/tickets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/features/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/features">> = Specific
  const handler = {} as typeof import("../../../src/app/api/features/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/healthz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/healthz">> = Specific
  const handler = {} as typeof import("../../../src/app/api/healthz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/platform-versions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform-versions/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/platform-versions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/platform-versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform-versions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/platform-versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/roadmap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roadmap">> = Specific
  const handler = {} as typeof import("../../../src/app/api/roadmap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sessions/[sessionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sessions/[sessionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sessions/[sessionId]/turns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[sessionId]/turns">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sessions/[sessionId]/turns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/team/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team">> = Specific
  const handler = {} as typeof import("../../../src/app/api/team/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tickets/[ticketId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tickets/[ticketId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tickets/[ticketId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tickets/reorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tickets/reorder">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tickets/reorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tickets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tickets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tickets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/versions/[versionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/versions/[versionId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/versions/[versionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/versions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/voices/[id]/archive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voices/[id]/archive">> = Specific
  const handler = {} as typeof import("../../../src/app/api/voices/[id]/archive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/voices/[id]/attempts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voices/[id]/attempts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/voices/[id]/attempts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/voices/[id]/extract/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voices/[id]/extract">> = Specific
  const handler = {} as typeof import("../../../src/app/api/voices/[id]/extract/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/voices/[id]/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voices/[id]/preview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/voices/[id]/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/voices/[id]/previews/[previewId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voices/[id]/previews/[previewId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/voices/[id]/previews/[previewId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/voices/[id]/previews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voices/[id]/previews">> = Specific
  const handler = {} as typeof import("../../../src/app/api/voices/[id]/previews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/voices/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voices/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/voices/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/voices/elevenlabs/presets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voices/elevenlabs/presets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/voices/elevenlabs/presets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/voices/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voices/providers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/voices/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/voices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voices">> = Specific
  const handler = {} as typeof import("../../../src/app/api/voices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/wiki/[id]/ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wiki/[id]/ingest">> = Specific
  const handler = {} as typeof import("../../../src/app/api/wiki/[id]/ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/wiki/[id]/ingest/runs/[runId]/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wiki/[id]/ingest/runs/[runId]/events">> = Specific
  const handler = {} as typeof import("../../../src/app/api/wiki/[id]/ingest/runs/[runId]/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/wiki/[id]/prompt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wiki/[id]/prompt">> = Specific
  const handler = {} as typeof import("../../../src/app/api/wiki/[id]/prompt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/wiki/[id]/prompt/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wiki/[id]/prompt/test">> = Specific
  const handler = {} as typeof import("../../../src/app/api/wiki/[id]/prompt/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/wiki/[id]/run-diff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wiki/[id]/run-diff">> = Specific
  const handler = {} as typeof import("../../../src/app/api/wiki/[id]/run-diff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/wiki/pages/[id]/source-refs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wiki/pages/[id]/source-refs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/wiki/pages/[id]/source-refs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/world-sessions/[sessionId]/audio/[artifactId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/world-sessions/[sessionId]/audio/[artifactId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/world-sessions/[sessionId]/audio/[artifactId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/world-sessions/[sessionId]/audio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/world-sessions/[sessionId]/audio">> = Specific
  const handler = {} as typeof import("../../../src/app/api/world-sessions/[sessionId]/audio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/world-sessions/[sessionId]/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/world-sessions/[sessionId]/events">> = Specific
  const handler = {} as typeof import("../../../src/app/api/world-sessions/[sessionId]/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/world-sessions/[sessionId]/orchestrate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/world-sessions/[sessionId]/orchestrate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/world-sessions/[sessionId]/orchestrate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/world-sessions/[sessionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/world-sessions/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/world-sessions/[sessionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/world-sessions/[sessionId]/turns/[turnId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/world-sessions/[sessionId]/turns/[turnId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/world-sessions/[sessionId]/turns/[turnId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/world-sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/world-sessions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/world-sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/worlds/[worldId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/worlds/[worldId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/worlds/[worldId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/worlds/build/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/worlds/build">> = Specific
  const handler = {} as typeof import("../../../src/app/api/worlds/build/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/worlds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/worlds">> = Specific
  const handler = {} as typeof import("../../../src/app/api/worlds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(authenticated)/characters/[slug]/harness/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/characters/[slug]/harness">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/harness/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/characters/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/characters/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/characters/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/wikis/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/wikis/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/wikis/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(authenticated)/worlds/[worldId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/worlds/[worldId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(authenticated)/worlds/[worldId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
